## Unit 5 Numpy_Random_Matrix Quiz
* The objective of this quiz is to use Numpy for generating random values and look at simple array manipulation.

In [2]:
## Import Numpy and check version
import numpy as np
print(f"Numpy version is {np.__version__}")

Numpy version is 2.1.3


### Random numbers are frequently used in Data Science.
* Generating random numbers (or rather pseudo-random numbers) is an important function.
* Numpy provides a random number module called `numpy.random`.
* You can learn more about generating random numbers [here](https://numpy.org/doc/stable/reference/random/index.html) and [here](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random).

### Create a random number generator called `my_rng` using the `default_rng()` method in `np.random`. Use the default seed.

In [ ]:
# Write your code below.
my_rng =  np.random.default_rng()
#print(type(my_rng))

<class 'numpy.random._generator.Generator'>


### Now use `my_rng` to generate a 3X3 numpy array of random values.
* Print out this array

In [ ]:
# Write your code below.
arr = my_rng.random((3,3)) 
# here we are asking the generator to produce a 3x3 matrix with random numbers
# Also passing the size in tuples, because numpy accepts dimensions in tuples
print("Generating random array with 3x3 dimension: \n", arr)
#print(type(arr))

(3, 3)
Generating random array with 3x3 dimension: 
 [[0.86008022 0.91355805 0.89642302]
 [0.483281   0.17221022 0.71512164]
 [0.85623632 0.31150054 0.85941956]]


### What is the distribution of the random numbers generated and what is the range?
* This is not something to be computed, simply look up this information in the [`np.random` web page](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html).

In [4]:
# Answer below
print("Random samples from a uniform distribution."+ "\n"+
"Range is [0,1) where 0 is inclusive and 1 is exclusive")

Random samples from a uniform distribution.
Range is [0,1) where 0 is inclusive and 1 is exclusive


### Use the Numpy array created above to create a second Numpy array of random numbers that is between -10.0 and 10.0.
* This question requires you to figure out the mapping that will convert a set of random numbers that are distributed as found in the previous question to have the range from -10.0 to 10.0.
* The form of the distributon does not change.

In [5]:
# Show your code below.
#using interp() method
arr = np.interp(arr,(arr.min(),arr.max()),(-10,10))
print("Generating random array with a range of (-10,10): \n", arr)

Generating random array with a range of (-10,10): 
 [[  5.6320984    9.08136836  10.        ]
 [ -1.924675     2.89361749   5.11460983]
 [-10.          -0.13692213   2.30022729]]


### `np.random` can also generate random integers. Generate a 3X3 array of random integers between 0 and 10.

In [6]:
# Your code here.
#randint(start,stop(exclusive),nxn array)
ran_within_10 = np.random.randint(0,11,size=(3,3))
print("Generating random array with a ranint function: \n",ran_within_10)

Generating random array with a ranint function: 
 [[3 3 1]
 [7 6 1]
 [6 8 0]]


### `np.random` can also generate various common distributions. Generate a 3X3 array of numbers from a normal distribution with mean 10 and standard deviation 2.

In [7]:
# Your code here
mean = 10
std = 2
arrdim = (3,3)

gm3 = my_rng.normal(loc = mean, scale = std, size = arrdim)
print("Generating normal distributed array of mean=10, std=2 and size=(3x3) : \n",gm3)

Generating normal distributed array of mean=10, std=2 and size=(3x3) : 
 [[ 9.0379012  12.12790076  9.43164726]
 [ 9.36580444  8.57319429 14.60679643]
 [12.0212477  12.74742982  7.34955104]]


### Call the 3X3 matrix of normal random variables generated in the last step `gm3`.
* Use Numpy methods to create two other numpy arrays, `row_sum` and `col_sum`:
* `row_sum` should be the length 3 array of the sum of the rows of `gm3`.
* `col_sum` should be the length 3 array of the sum of the columns of `gm3`

In [8]:
# Your code here
row_sum = gm3.sum(axis=1)
print("Sum of rows of gm3 with length 3: \n",row_sum)

col_sum = gm3.sum(axis=0)
print("Sum of columns of gm3 with length 3: \n",col_sum)

Sum of rows of gm3 with length 3: 
 [30.59744921 32.54579516 32.11822856]
Sum of columns of gm3 with length 3: 
 [30.42495334 33.44852487 31.38799472]
