# Graded: 7 of 7 correct
- [x] Array `A`: (3,3) random ints
- [x] Array `b`: (3,) random ints
- [x] `A * b`
- [x] Explanation of `A * b`: show broadcast versions
- [x] Array `c`: (2,) random ints
- [x] `A * c`
- [x] Explanation of `A * c`

Comments:


## Unit 5 Numpy_Broadcast Quiz
* The objective of this quiz is to understand how to use how broadcasting works with Numpy arrays.

In [1]:
## Import Numpy and check version
import numpy as np
print(f"Numpy version is {np.__version__}")

Numpy version is 2.1.3


## Broadcasting is a feature of Numpy arrays that allows arithmetic operations between arrays that are not necessarily of compatible dimension for the computation.
* During such an operation, the arrays are "broadcast" to a certain size that makes the operartion possible.
* Knowledge of broadcasting is useful in a number of places, for example deep learning methids.

## Create  a Numpy array `A` as a (3, 3) array of random integers.

In [2]:
# Your code here
A = np.random.randint(0,10,(3,3))
print("Array of 3x3: ", A)

Array of 3x3:  [[4 3 7]
 [8 0 8]
 [9 7 7]]


## Create a second numpy array, `b` of size (3,) of random integers.

In [3]:
# Your code here
B = np.random.randint(2,20,(3,))
print("Second Array of size (3,): ", B)

Second Array of size (3,):  [8 7 2]


## Perform the operation `A*b`

In [4]:
# Your code below
print("A*B=",np.multiply(A,B))


A*B= [[32 21 14]
 [64  0 16]
 [72 49 14]]


## Explain why it was possible to compute `A*b` in the above case. 
* As part of your explanation, show the broadcast versions of `A` and `b`

### Explanation here.
Numpy align dimension from right to left  
 shape of A is 3x3  
 shape of B is 1x3  
 First dimension 3 vs 1 ->According to boardcast rule, the aligned shape should be compatible or 1  ========>So 1 broadcasted to 3    
 second dimension 3 vs 3 ->compatible so 3

 So B boardcasted from (3,) ->(1,3)->(3,3)

 Initially B : [b0,b1,b2]

 After boardcasting B: [[b0,b1,b2],
                        [b0,b1,b2],
                        [b0,b1,b2]]

Then it performs multiplication operation

 


## Now create a third array `c` that is a (2,) array of random integers.

In [5]:
# Your code here

c = np.random.randint(1, 6,(2,))
print("Third array c is ",c)

Third array c is  [3 5]


## Perform the operation `A*c`

In [6]:
# Your code here

print("A*c=", np.multiply(A,c))

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

## Explain, in terms of broadcasting, why it was not possible to compute `A*c`

### Your explanation here.

#### Boardcasting Alignment:   
Shape A: 3 , 3  
Shape C: 1, 2 (alinged from `right to left`)  

First dimension 3 vs 2:   
According to boardcasting rule, the aligned shape should be either  compatible or 1, `3 vs 2` fails both the conditions, its throwning `ValueError`.
