In [57]:
import numpy as np

### Range():
-Syntax: 
`Range(start,stop, step)`

In [58]:
countOf10 = range(10)
print(countOf10)

range(0, 10)


### Comparing with arange of in numpy 
`note:` its aRange of not aRRange
np.arange() creates a range of numbers passed as parameter.

#### syntex:
`np.arange(start,stop,step)`

In [59]:
npCountOf10  =  np.arange(10)
print(npCountOf10)

[0 1 2 3 4 5 6 7 8 9]


#### Numpy arrays are all same datatype.

All elements in an array of numpy must be same data type.
Assume if the first element arr[0] is an integer than the ellemts in the array will hold only integer value.
Where `list` in python are `heterogenous` which holds different datatype, the `array` in numpy are `homogeneous` data types.
Lets see an example below trying to insert an float value in an integer array of numpy.

In [60]:
## creating an array using numpy

arr = np.arange(15)
print(arr)

## checking the length of array using len() function
print(len(arr))

## inserting a float value in the middle of an integer array

arr[(len(arr) // 2)] = 36.5
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
15
[ 0  1  2  3  4  5  6 36  8  9 10 11 12 13 14]


In the above resulting array , you can notice that the `float value` is inserted as integer since the numpy array holds same type, it converts the `float` to `int` and inserted to the index specified.

Since float is a numeric value it converted it to Integer.
whatif we assign a value that cant be converted in integer?

In [61]:
arr[4]="arr"
print(arr)

ValueError: invalid literal for int() with base 10: 'arr'

The above trying to insert the string value , which cant be converted so throwing  `ValueError`.
Since it throwing error enclosing it in the `try except` for smooth running of the program.

In [ ]:
import sys
try:
    arr[4]="arr"
    print(arr)
except:
    print("Exception :", sys.exc_info()[1])
    pass


Exception : invalid literal for int() with base 10: 'arr'


#### Numpy has zeros() to have zero array
##### Syntax:
`np.zeros(num,dtype=float)` 

it takes two arg first takes number of elements, second parameter is `dtype` , which is by default assign to `float`. If we want we can change into int or bool `dtype=int`,`dtype=bool` . we can see all examples below.


In [ ]:
## this gives float value.
zeroArr = np.zeros(10)
print("float value array:",zeroArr)

## changing to int type
zeroArrInt = np.zeros(10,dtype=int)
print("Integer value array:",zeroArrInt)

## changing to bool data type
zeroArrBool = np.zeros(5,dtype=bool)
print("Boolean value array:",zeroArrBool)

## Creating another bool array in different way
anotherBool = np.array([False]*5)
print("Boolean value array:",anotherBool)




float value array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Integer value array: [0 0 0 0 0 0 0 0 0 0]
Boolean value array: [False False False False False]
Boolean value array: [False False False False False]


#### np.any and np.all
-`np.any` - evaluates if any one element in both array matches   
-`np.all` - evaluates wether all the elements in both the arrays matches  
-syntax:       
`np.any(first array `==` second array)`        
`np.all(first array `==` second array)`

In [ ]:
any_element_matches = np.any(zeroArrBool == anotherBool)
all_element_matches = np.all(zeroArrBool == anotherBool)
print("Any elements in two array matched: ", any_element_matches)
print("All elements in two array matched: ", all_element_matches)

Any elements in two array matched:  True
All elements in two array matched:  True


#### Lets read a co2 emission pickle file


In [ ]:
import pickle
import comp116
with open("Co2_emission.pickle",'rb') as f:
    # data = pickle.load(f)
    # print(len(data))
    # print(data[0])
    # print(data[1])
    # print(data[2])
    # print(data[3])

    years,us_coal,us_petrol,us_nat_gas = pickle.load(f)

# importing cop116 to convert the array into hml
#Syntax : def array_to_html(arr, row_names=None, col_names=None, title=None):

comp116.array_to_html(us_coal, row_names=years, col_names=['Coal CO2'],
                      title='United States CO2 emmissions from coal in millions of metric tons')

,Coal CO2
2016,1341.554505
2015,1466.690348
2014,1697.674855
2013,1701.695889
2012,1639.630926
2011,1855.156011
2010,1965.117129
2009,1858.135179
2008,2113.011264
2007,2147.475127


In [ ]:
over_two_billion_co2_emission = np.any(us_coal>2000)
print(over_two_million_co2_emission)

True


In [65]:
always_over_two_billion_tons = np.all(us_coal>2000)
print(always_over_two_billion_tons)

False


In [66]:
## finding the minimum us_coal emission
min_coal = min(us_coal)
print("Minimum coal emission among the years: ", min_coal)

Minimum coal emission among the years:  1341.554505


In [67]:
## getting the offset/index of the minimum coal emission
offset_min_coal = np.argmin(us_coal)
print(offset_min_coal)

0


In [71]:
# To find the year of the minimum offset
yearOfMinOffset = years[0]
print(yearOfMinOffset)

# Another way finding the year of minimum coal emission
min_year_offset = years[offset_min_coal]
print(min_year_offset)

2016
2016


In [72]:
# the count_nonzero function gives the non-zero values in the array
countOfemission_two_billiontons = np.count_nonzero(us_coal>2000)
print(countOfemission_two_billiontons)

12


In [74]:
## Finding the maximum co2 emission
max_emission = np.max(us_coal)
print("Maximum co2 emission:",max_emission)

Maximum co2 emission: 2151.634481


In [76]:
## Finding the average of the co2 emission
avg_emission = np.average(us_coal)
print("Average co2 emission:",avg_emission)

Average co2 emission: 1827.5202682972972
