In [9]:
import numpy as np
A=  np.array([3,4,6,10,24,89,45,43,46,99,100])
#which are not divisible by 3
B = A[(A%3 != 0)]
print("which are not divisible by 3: \n", B)

which are not divisible by 3: 
 [  4  10  89  43  46 100]


In [10]:
#which are divisible by 5

c =A[(A%5 == 0)] 
print("which are divisible by 5: \n", c)


which are divisible by 5: 
 [ 10  45 100]


In [11]:
# which are divisible 3 and 5
D = A[(A%3==0)&(A%5==0)]
print("which are divisible by 3 and 5: \n", D)

which are divisible by 3 and 5: 
 [45]


In [14]:
#which are divisible by 3 and set them to 42

A[A%3==0] = 42
print("which are divisible by 3 and set them to 42: \n",A)


which are divisible by 3 and set them to 42: 
 [ 42   4  42  10  42  89  42  43  46  42 100]


In [22]:
import numpy as np

a = np.array([[0, 2, 3, 0, 1],
              [1, 0, 0, 7, 0],
              [5, 0, 0, 1, 0]])

print(a.nonzero())
print(np.transpose(a.nonzero()))

#non-zero values can be retrieved using below code
print(a[a.nonzero()])
#flatnonzero
print(np.flatnonzero(a))
print(np.count_nonzero(a))


(array([0, 0, 0, 1, 1, 2, 2]), array([1, 2, 4, 0, 3, 0, 3]))
[[0 1]
 [0 2]
 [0 4]
 [1 0]
 [1 3]
 [2 0]
 [2 3]]
[2 3 1 1 7 5 1]
[ 1  2  4  5  8 10 13]
7
